version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml appspec.yml --s3-bucket hello-test-1992 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
    - appspec.yml
